### ISSUE TITLE
Claw code

### ISSUE THREAD

**Issue by DekuLord** [BuffRobotics2018/Current-Events-Robot-Programs#3]
Program the claw to close and open.

**Comment by sumitkp18** [comment]
Hi, I am interested to contribute. Could you help me  on **where to start**?

**Comment by DekuLord** [comment]
Yeah, sure. I'm not exactly sure what the claw will look like (still
waiting for the building team to finish) but I believe it will drop down
from the end of our extendable arm. The shape is hard to explain. I'll try
to find a picture to show you. But thanks anyways!

Trang

**Comment by DekuLord** [comment]
Just so you know, we are doing this as part of a competition, so there is a possibility that we might not be able to accept contributions from other people. But if we are, the help would be great.
